services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - pg-matchpoint:/var/lib/postgresq/data
networks:
  backend:
volumes:
  pg-matchpoint:
