# Generated by Django 6.0.7 on 2026-08-01 06:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptionalunavailability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionalunavailability',
            name='end_datetime',
            field=models.DateTimeField(validators=[common.validators.Is30MinutesIncrement()]),
        ),
        migrations.AlterField(
            model_name='exceptionalunavailability',
            name='start_datetime',
            field=models.DateTimeField(validators=[common.validators.Is30MinutesIncrement()]),
        ),
    ]
