# Generated by Django 6.0.7 on 2026-07-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_remove_reservation_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_amt",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
