# Generated by Django 6.0.7 on 2026-08-01 06:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closing_hour',
            field=models.TimeField(validators=[common.validators.Is30MinutesIncrement()]),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='opening_hour',
            field=models.TimeField(validators=[common.validators.Is30MinutesIncrement()]),
        ),
    ]
