# Generated by Django 6.0.7 on 2026-08-02 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0014_alter_club_email_alter_club_phone"),
        ("openinghours", "0002_alter_openinghours_closing_hour_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openinghours",
            unique_together={("club", "weekday")},
        ),
    ]
