# Generated by Django 6.0.7 on 2026-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_remove_profile_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
