# Generated by Django 6.0.7 on 2026-08-31 13:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0005_alter_court_name_alter_court_sport_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255, null=True)),
                (
                    "pending_image",
                    models.ImageField(blank=True, null=True, upload_to="tmp/courts/"),
                ),
                (
                    "court_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="courts.court",
                    ),
                ),
            ],
        ),
    ]
