# Generated by Django 6.0.7 on 2026-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0006_courtimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtimages",
            name="image",
            field=models.CharField(null=True),
        ),
    ]
