# Generated by Django 6.0.7 on 2026-08-31 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0007_alter_courtimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtimages",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
