# Generated by Django 6.0.7 on 2026-09-01 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0008_alter_courtimages_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courtimages",
            name="pending_image",
        ),
        migrations.AlterField(
            model_name="courtimages",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
