# Generated by Django 6.0.7 on 2026-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0009_remove_courtimages_pending_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtimages",
            name="image",
            field=models.ImageField(upload_to="courts"),
        ),
    ]
