# Generated by Django 6.0.7 on 2026-08-28 19:37

import cloudinary.models
import common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_club_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='header_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[common.validators.CustomImageFormatValidator()]),
        ),
    ]
