# Generated by Django 6.0.7 on 2026-08-29 13:22

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_club_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='header_image',
            field=models.ImageField(null=True, upload_to='', validators=[common.validators.CustomImageFormatValidator()]),
        ),
    ]
