# Generated by Django 6.0.7 on 2026-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0021_alter_club_pending_header_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="pending_header_image",
        ),
        migrations.AlterField(
            model_name="club",
            name="header_image",
            field=models.ImageField(null=True, upload_to="clubs/"),
        ),
    ]
